---
language: generic
stages:
  - lint
  - build and deploy
jobs:
  include:
    - stage: lint
      name: omnilint
      install: docker pull lpenz/omnilint
      script: docker run --rm -u "$UID" -v "$PWD:$PWD" -w "$PWD" lpenz/omnilint
    - stage: build and deploy
      install: docker build -t cv .
      script:
        - docker run --rm -u "$UID" -w "$PWD" -v "$PWD:$PWD" cv
        # Remove devel .gitignore directive so that built files are commited to master
        - rm -f .gitignore
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: "$GITHUB_TOKEN"
        target-branch: gh-pages
        on:
          branch: master
