version: 2

jobs:
  test:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command: pip install -r requirements.txt
      - run:
          name: System dependencies
          command: apt-get update && apt-get install -y pandoc
      - run:
          name: Setup output environment
          command: |
            mkdir dist
            cp -r assets/css dist 
            cp -r assets/fontawesome dist
            cp -r assets/images dist
      - run:
          name: Build DevResume CV view
          command: python ./tools/jinja2-render -y fluz.yml -o dist/cv.html DevResume/index.html.jinja
workflows:
  version: 2
  build:
    jobs:
      - test 