version: 2

jobs:
  cv-builds:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command: pip install -r requirements.txt
      - run:
          name: System dependencies
          command: apt-get update && apt-get install -y pandoc
      - run:
          name: Setup output environment
          command: |
            mkdir dist
            cp -r assets/css dist 
            cp -r assets/fontawesome dist
            cp -r assets/images dist
            cp -r assets/js dist
      - run:
          name: Build DevResume CV view
          command: python ./tools/jinja2-render -y fluz.yml -o dist/cv.html DevResume/index.html.jinja
      - run:
          name: Build CeeVee CV view
          command: python ./tools/jinja2-render -y fluz.yml -o dist/cv_ceevee.html ceevee/index.html.jinja
      - run:
          name: Build Markdown view
          command: python ./tools/jinja2-render -y fluz.yml -o dist/cv_fernando_luz.md markdown/cv.md.jinja
      - run:
          name: Build Markdown HTML view
          command: pandoc -f markdown -t html -V "pagetitle:Fernando Luz's Resume" -s --css templates/default.css -o dist/cv_fernando_luz_md.html dist/cv_fernando_luz.md
      - run:
          name: Build Markdown text view
          command: pandoc -f markdown -t plain -s -o dist/cv_fernando_luz_md.txt dist/cv_fernando_luz.md
      - persist_to_workspace:
          root: .
          paths: dist
  cv-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Disable jekyll builds
          command: touch dist/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@fluz.net"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "67:10:37:41:ef:79:6b:2c:73:bf:b7:31:1f:2b:e6:bb"
      - run:
          name: Deploy CVs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] CV Updates" --dist ./dist 

workflows:
  version: 2
  build:
    jobs:
      - cv-builds
      - cv-deploy:
          requires:
            - cv-builds
          filters:
            branches:
              only: Circle-Ci