version: 2

jobs:
  test:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: echo "pip install -r requirements.txt"
      - run:
          name: Test
          command: echo "Running test"
workflows:
  version: 2
  build:
    jobs:
      - test